### PR TITLE
Adding the start of doc generation

### PR DESCRIPTION
**Pull request by gauntface**
cc @wibblymat 

This just adds a jsdoc configuration file and an npm script to build docs.

### CODE REVIEW

**Comment by gauntface** [comment]
cc @wibblymat @addyosmani

**Comment by gauntface** [comment]
Anyone free for a review? @wibblymat @addyosmani @jeffposnick @sgomez @surma

**Comment by surma** [comment]
LGTM :wink:

**Comment by wibblymat** [comment]
LGTM

(Aside: @gauntface pretty sure you have the wrong Sérgio - our's is Gomes not Gomez :wink:)

**Comment by gauntface** [comment]
Argh!! I always do that with Sergio :(

**Comment by addyosmani** [comment]
Late LGTM3 :)

**Pull request merged**
