### PR TITLE
Adding tests for sendWebPush

### PR DESCRIPTION
**Pull request by wibblymat**
@gauntface This is your PR #11 which I have rebased, fixed after changes on master, and then made a few small changes to.

Biggest functional change is that `encrypt` now let's `message` be a `String` or a `Buffer`. It should really have been in it's own PR, I guess, but I thought of it while doing this one. `¯\_(ツ)_/¯`

### CODE REVIEW

**Comment by wibblymat** [comment]
@googlebot <iframe width="560" height="315" src="https://www.youtube.com/embed/pWdd6_ZxX8c" frameborder="0" allowfullscreen></iframe>

[Yeah, well, you know, that's just like, uh, your opinion, man](https://www.youtube.com/watch?v=pWdd6_ZxX8c)

**Comment by gauntface** [comment]
@wibblymat what do you want to do about this?

**Comment by wibblymat** [comment]
It's not a big deal, we just override the check. We just have to make sure
that WE believe that everyone has signed a CLA. It was only when we had the
strictest form of branch protection on that it was a problem.

**Comment by gauntface** [comment]
LGTM from me.

**Pull request merged**
